### ISSUE TITLE
Link broken on website

### ISSUE THREAD

**Issue by zx8754** [cooljeanius/gcta#1]
http://cnsgenomics.com/software/gcta/#Gene-basedtest

Link to this file is broken:
http://cnsgenomics.com/software/gcta/glist-hg18.txt

**Comment by cooljeanius** [comment]
The website isn't actually part of this repo; it's just where I got the code from...

**Comment by zx8754** [comment]
Sorry, I thought you were the author, didn't know where else to report the broken link.
