### ISSUE TITLE
Suggest: add example files to allow documentation examples to run

### ISSUE THREAD

**Issue by richelbilderbeek** [cooljeanius/gcta#4]
Dear GCTA maintainer,

Here I suggest to add some example files to allow a new user to run all example code.

At [https://cnsgenomics.com/software/gcta/#GWASSimulation](https://cnsgenomics.com/software/gcta/#GWASSimulation) I find some examples how to simulate GWAS data:

```
# Simulate a quantitative trait with the heritability of 0.5 for a subset of individuals for 3 times
gcta64  --bfile test  --simu-qt  --simu-causal-loci causal.snplist  --simu-hsq 0.5 --simu-rep 3  --keep test.indi.list --out test
# Simulate 500 cases and 500 controls with the heritability of liability of 0.5 and disease prevalence of 0.1 for 3 times
gcta64  --bfile test  --simu-cc 500 500  --simu-causal-loci causal.snplist  --simu-hsq 0.5  --simu-k 0.1  --simu-rep 3  --out test
```

What is missing in both cases are the example files `test.indi.list` and `causal.snplist`. I suggest to add these, so a new user can have an idea what these files should look like.

**Comment by cooljeanius** [comment]
Again, not a maintainer, but I guess I can look at adding these...

**Comment by richelbilderbeek** [comment]
@cooljeanius Hi Erik, thanks for your help! I am unsure how the labor is distributed. I feel it may be more fair to email Jian Yang directly to point him to my Issues, as I feel he is not Watching this repo (i.e. he does not get an email from GitHub when an Issue is created). Would that be better in the grand scheme of things?

**Comment by cooljeanius** [comment]
yes, it would probably be better to email Jian

**Comment by richelbilderbeek** [comment]
Hmmm, I interpret from your recent commit [here](https://github.com/cooljeanius/gcta/blame/master/README.txt#L25) that this may not be the version of GCTA that is maintained by Jian? What is the actual status of GCTA here? Is Jian still involved, or has he abandoned GCTA?

**Comment by cooljeanius** [comment]
I have never contacted Jian myself; I don't know what they've been up to lately

**Comment by richelbilderbeek** [comment]
Hmmm, for my own needs, I use the [plinkr](https://github.com/richelbilderbeek/plinkr#plinkr) package now. It is actively maintained, tested well and even has YouTube video. Disclaimer: I am the maintainer :-)

Closing this Issue :+1:
